on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-version:
    runs-on: ubuntu-latest
    steps:
    - name: Show Python version
      run: python --version

  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Sprawdź Kod
      uses: actions/checkout@v2
    - name: Skonfiguruj Pythona
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Zainstaluj zależności
      run: pip install -r requirements.txt
    - name: Wystartuj Pylint
      run: pylint app.py
